# Generated by Django 4.2 on 2023-04-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_card_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
