# Generated by Django 4.2 on 2023-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_card_app', '0002_entry_delete_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
