# Generated by Django 4.2 on 2023-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_card_app', '0006_alter_entry_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='linkedin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
