# Generated by Django 4.2 on 2023-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_card_app', '0008_alter_entry_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='linkedin',
            field=models.URLField(),
        ),
    ]
