# Generated by Django 4.2 on 2023-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_card_app', '0009_alter_entry_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
